name: projectassignment
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  connectivity_plus: ^6.0.3
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:
  uses-material-design: true

  assets:
    - assets/icons/


#---------------LOCAL FONTS---------------#
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
